package kbc;
import sun.audio.*;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import java.util.Timer;
import java.util.TimerTask;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
public class Front extends javax.swing.JFrame {
int counter =1;
Timer timer, timer2 ;
TimerTask task, task2; 
int sec,x;
int optionCounter;
 InputStream in;
    public Front() {
        initComponents();
    }
   public void start(){
        x=30;
        timer=new Timer();
        task=new TimerTask(){
            @Override
             public void run(){
               x--;
                ss.setText(x+"");
                if(x==0){
                    jPanel1.setVisible(false);
                    jMenuBar1.setVisible(false);
                    diagmsg.setVisible(true);
                    jMenuBar1.setVisible(true);
                   timer.cancel();
                }
               try{
            in=new FileInputStream(new File("C:\\Users\\dell\\Documents\\NetBeansProjects\\KBC\\build\\classes\\sound\\tick.wav"));
        AudioStream audios = new AudioStream(in);
        AudioPlayer.player.start(audios);
         
        }
        catch(Exception e){
          timer.cancel();
           
        }
            }            
        };
          timer.scheduleAtFixedRate(task,2000, 1000);
   }
   
   public void restart(){
       x=31;
       timer.cancel();
       
       timer=new Timer();
        task=new TimerTask(){
            @Override
             public void run(){
               x--;
                ss.setText(x+"");
                if(x==0){
                    jPanel1.setVisible(false);
                    jMenuBar1.setVisible(false);
                    diagmsg.setVisible(true);
                    jMenuBar1.setVisible(true);
                   timer.cancel();
                }
                try{
            in=new FileInputStream(new File("C:\\Users\\dell\\Documents\\NetBeansProjects\\KBC\\build\\classes\\sound\\tick.wav"));
        AudioStream audios = new AudioStream(in);
        AudioPlayer.player.start(audios);
         
        }
        catch(Exception e){
          timer.cancel();
           
        }
            }                
        };
  timer.schedule(task,0,1000);
   }
   
   public void conitnue(){
       x=Integer.parseInt(ss.getText());
       timer=new Timer();
       task= new TimerTask(){
         @Override
         public void run(){
             x--;
             ss.setText(x+"");
             if(x==0){
                    jPanel1.setVisible(false);
                    jMenuBar1.setVisible(false);
                    diagmsg.setVisible(true);
                    jMenuBar1.setVisible(true);
                   timer.cancel();
             }
             try{
            in=new FileInputStream(new File("C:\\Users\\dell\\Documents\\NetBeansProjects\\KBC\\build\\classes\\sound\\tick.wav"));
        AudioStream audios = new AudioStream(in);
        AudioPlayer.player.start(audios);
         
        }
        catch(Exception e){
          timer.cancel();
           
        }
         }
       };
        timer.schedule(task,0,1000);
   }
   public void stop(){
       timer.cancel();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ll1 = new javax.swing.JButton();
        ll2 = new javax.swing.JButton();
        ll3 = new javax.swing.JButton();
        mt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        a = new javax.swing.JButton();
        b = new javax.swing.JButton();
        c = new javax.swing.JButton();
        d = new javax.swing.JButton();
        ques = new javax.swing.JLabel();
        hh = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ss = new javax.swing.JLabel();
        diagmsg = new javax.swing.JLayeredPane();
        msg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setName("Kaun Banega Crorepati"); // NOI18N

        ll1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/life_line/5050.jpg"))); // NOI18N

        ll2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/life_line/audience.jpg"))); // NOI18N

        ll3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/life_line/phone'.jpg"))); // NOI18N
        ll3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ll3FocusGained(evt);
            }
        });

        mt.setBackground(new java.awt.Color(0, 0, 0));
        mt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money_tree/0.jpg"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kbc/logo.jpg"))); // NOI18N
        jLabel1.setName("KBC"); // NOI18N

        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/1/1a.jpg"))); // NOI18N
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/1/1b.jpg"))); // NOI18N
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/1/1c.jpg"))); // NOI18N
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/1/1d.jpg"))); // NOI18N
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/1/1.jpg"))); // NOI18N

        hh.setFont(new java.awt.Font("Ebrima", 0, 50)); // NOI18N
        hh.setForeground(new java.awt.Color(0, 0, 255));
        hh.setText("00");

        jLabel3.setFont(new java.awt.Font("Ebrima", 0, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(":");

        ss.setFont(new java.awt.Font("Ebrima", 0, 50)); // NOI18N
        ss.setForeground(new java.awt.Color(0, 0, 255));
        ss.setText("30");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ques))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(hh, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ll1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ll2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ll3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mt))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ques, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ll2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ll1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ll3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ss)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mt, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        diagmsg.setPreferredSize(new java.awt.Dimension(975, 678));

        msg.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        msg.setText("Time Out !!!");

        diagmsg.setLayer(msg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout diagmsgLayout = new javax.swing.GroupLayout(diagmsg);
        diagmsg.setLayout(diagmsgLayout);
        diagmsgLayout.setHorizontalGroup(
            diagmsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagmsgLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(msg)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        diagmsgLayout.setVerticalGroup(
            diagmsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagmsgLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(msg)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Play          ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Instruction");
        jMenu2.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("About            ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diagmsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diagmsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void aActionPerformed(java.awt.event.ActionEvent evt) {                                  
       
        if(counter==1){ 
            optionCounter=0;
            counter++;
          timer.cancel();
            timer2=new Timer();
            task2 =new TimerTask(){
             @Override
             public void run(){
                  
                    optionCounter++;
              if(optionCounter%2==0){
                  jPanel1.setBackground(Color.green);
                   }
              else {
                  if(optionCounter==7){
                      
                      timer2.cancel();
                      restart();
                   jPanel1.setBackground(Color.black);
             
             ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/2/2.jpg")));
             mt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money_tree/5.jpg")));
             a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/2/2a.jpg")));
             b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/2/2b.jpg")));
             c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/2/2c.jpg")));
             d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/2/2d.jpg")));
                  }
                  
              }
            ;
         }        
         };
         timer2.schedule(task2,0,500);                                           
       }
        else if(counter==9){
              optionCounter=0;
          timer.cancel();
          timer2=new Timer();
          task2= new TimerTask(){
              @Override
              public void run(){
                  optionCounter++;
               if(optionCounter%2==0){
                  jPanel1.setBackground(Color.green); 
               }
               else if(optionCounter==7){
                      timer2.cancel();
                      restart();
                   jPanel1.setBackground(Color.black);
             counter++;
             ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/10/10.jpg")));
             mt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money_tree/1250.jpg")));
             a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/10/10a.jpg")));
             b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/10/10b.jpg")));
             c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/10/10c.jpg")));
             d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/10/10d.jpg")));
                  }
              }       
          };
          timer2.schedule(task2,0,500);
       
        }
        else {
 
 jPanel1.setBackground(Color.RED);
 timer.cancel();
 a.setVisible(false);
 b.setVisible(false);
 c.setVisible(false);
 d.setVisible(false);
 
          }
    }                                 

    private void dActionPerformed(java.awt.event.ActionEvent evt) {                                  
    
        if(counter==6){
            optionCounter=0;
            timer.cancel();
            timer2= new Timer();
            task2=new TimerTask(){
                @Override
                public void run(){
                  optionCounter++;
                  if(optionCounter%2==0){
                      jPanel1.setBackground(Color.green);
                  }
                  else if(optionCounter==7){
                      timer2.cancel();
                      restart();
                      jPanel1.setBackground(Color.black);
                      counter++;
                      ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/7/7.jpg")));
                      mt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money_tree/160.jpg")));
                      a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/7/7a.jpg")));
                      b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/7/7b.jpg")));
                      c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/7/7c.jpg")));
                      d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/7/7d.jpg")));
                  }
                }
            };
            timer2.scheduleAtFixedRate(task2,0,500);
        }
        
        else if(counter==12){
              optionCounter=0;
          timer.cancel();
          timer2=new Timer();
          task2= new TimerTask(){
              @Override
              public void run(){
                  optionCounter++;
               if(optionCounter%2==0){
                  jPanel1.setBackground(Color.green); 
               }
               else if(optionCounter==7){
                      timer2.cancel();
                      restart();
                   jPanel1.setBackground(Color.black);
             counter++;
             ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/12/12.jpg")));
             mt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money_tree/10000.jpg")));
             a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/12/12a.jpg")));
             b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/12/12b.jpg")));
             c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/12/12c.jpg")));
             d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/12/12d.jpg")));
                  }
              }       
          };
          timer2.schedule(task2,0,500);
       
        }
          
          
          else {
 
 jPanel1.setBackground(Color.RED);
 timer.cancel();
 a.setVisible(false);
 b.setVisible(false);
 c.setVisible(false);
 d.setVisible(false);
 
          }
        
    }                                 

    private void bActionPerformed(java.awt.event.ActionEvent evt) {                                  
       
          if(counter==2){
              optionCounter=0;
          timer.cancel();
          timer2=new Timer();
          task2= new TimerTask(){
              @Override
              public void run(){
                  optionCounter++;
               if(optionCounter%2==0){
                  jPanel1.setBackground(Color.green); 
               }
               else if(optionCounter==7){
                      timer2.cancel();
                      restart();
                   jPanel1.setBackground(Color.black);
             counter++;
             ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/3/3.jpg")));
             mt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money_tree/10.jpg")));
             a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/3/3a.jpg")));
             b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/3/3b.jpg")));
             c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/3/3c.jpg")));
             d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/3/3d.jpg")));
                  }
              }       
          };
          timer2.schedule(task2,0,500);
       
        }
          else if(counter==8){
              optionCounter=0;
          timer.cancel();
          timer2=new Timer();
          task2= new TimerTask(){
              @Override
              public void run(){
                  optionCounter++;
               if(optionCounter%2==0){
                  jPanel1.setBackground(Color.green); 
               }
               else if(optionCounter==7){
                      timer2.cancel();
                      restart();
                   jPanel1.setBackground(Color.black);
             counter++;
             ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/9/9.jpg")));
             mt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money_tree/640.jpg")));
             a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/9/9a.jpg")));
             b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/9/9b.jpg")));
             c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/9/9c.jpg")));
             d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/9/9d.jpg")));
                  }
              }       
          };
          timer2.schedule(task2,0,500);
       
        }
          
          
          else if(counter==3){
                optionCounter=0;
          timer.cancel();
          timer2=new Timer();
          task2= new TimerTask(){
              @Override
              public void run(){
                  optionCounter++;
               if(optionCounter%2==0){
                  jPanel1.setBackground(Color.green); 
               }
               if(optionCounter==7){
                      timer2.cancel();
                      restart();
                   jPanel1.setBackground(Color.black);
             counter++;
              ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/4/4.jpg")));
        mt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money_tree/20.jpg")));
        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/4/4a.jpg")));
         b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/4/4b.jpg")));
          c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/4/4c.jpg")));
           d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/4/4d.jpg")));
                  }
              }       
          };
          timer2.schedule(task2,0,500);
          }
          else if(counter==4){
                optionCounter=0;
          timer.cancel();
          timer2=new Timer();
          task2= new TimerTask(){
              @Override
              public void run(){
                  optionCounter++;
               if(optionCounter%2==0){
                  jPanel1.setBackground(Color.green); 
               }
               if(optionCounter==7){
                      timer2.cancel();
                      restart();
                   jPanel1.setBackground(Color.black);
             counter++;
              ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/5/5.jpg")));
        mt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money_tree/40.jpg")));
        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/5/5a.jpg")));
         b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/5/5b.jpg")));
          c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/5/5c.jpg")));
           d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/5/5d.jpg")));
                  }
              }       
          };
          timer2.schedule(task2,0,500);
          }
          else if(counter==7){
               optionCounter=0;
          timer.cancel();
          timer2=new Timer();
          task2= new TimerTask(){
              @Override
              public void run(){
                  optionCounter++;
               if(optionCounter%2==0){
                  jPanel1.setBackground(Color.green); 
               }
               if(optionCounter==7){
                      timer2.cancel();
                      restart();
                   jPanel1.setBackground(Color.black);
             counter++;
              ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/8/8.jpg")));
        mt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money_tree/320.jpg")));
        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/8/8a.jpg")));
         b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/8/8b.jpg")));
          c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/8/8c.jpg")));
           d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/8/8d.jpg")));
                  }
              }       
          };
          timer2.schedule(task2,0,500);
          }
          
          else if(counter==11){
              optionCounter=0;
          timer.cancel();
          timer2=new Timer();
          task2= new TimerTask(){
              @Override
              public void run(){
                  optionCounter++;
               if(optionCounter%2==0){
                  jPanel1.setBackground(Color.green); 
               }
               else if(optionCounter==7){
                      timer2.cancel();
                      restart();
                   jPanel1.setBackground(Color.black);
             counter++;
             ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/12/12.jpg")));
             mt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money_tree/5000.jpg")));
             a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/12/12a.jpg")));
             b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/12/12b.jpg")));
             c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/12/12c.jpg")));
             d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/12/12d.jpg")));
                  }
              }       
          };
          timer2.schedule(task2,0,500);
       
        }
          
          
          else {
 
 jPanel1.setBackground(Color.RED);
 timer.cancel();
 a.setVisible(false);
 b.setVisible(false);
 c.setVisible(false);
 d.setVisible(false);
 
          }
    }                                 

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
       
     
    InputStream in;
        try{
               new Front().setVisible(true);
       this.dispose();
       
       in= new FileInputStream(new File("C:\\Users\\dell\\Documents\\NetBeansProjects\\KBC\\build\\classes\\sound\\kbc.wav"));
        AudioStream audios = new AudioStream(in);
        AudioPlayer.player.start(audios);
        }
        catch(Exception e){
           new Front().setVisible(false);
           
        }
    }                                          

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
 
       System.exit(0);
    }                                          

                              

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
      
        new About().setVisible(true);
    }                                          

    private void cActionPerformed(java.awt.event.ActionEvent evt) {                                  
     
        if(counter==5){
          optionCounter=0;
          timer.cancel();
          timer2=new Timer();
          task2= new TimerTask(){
              @Override
              public void run(){
                  optionCounter++;
               if(optionCounter%2==0){
                  jPanel1.setBackground(Color.green); 
               }
               if(optionCounter==7){
                      timer2.cancel();
                      restart();
                   jPanel1.setBackground(Color.black);
             counter++;
              ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/6/6.jpg")));
        mt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money_tree/80.jpg")));
        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/6/6a.jpg")));
         b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/6/6b.jpg")));
          c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/6/6c.jpg")));
           d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/6/6d.jpg")));
                  }
              }       
          };
          timer2.schedule(task2,0,500);
        }
        else if(counter==10){
              optionCounter=0;
          timer.cancel();
          timer2=new Timer();
          task2= new TimerTask(){
              @Override
              public void run(){
                  optionCounter++;
               if(optionCounter%2==0){
                  jPanel1.setBackground(Color.green); 
               }
               else if(optionCounter==7){
                      timer2.cancel();
                      restart();
                   jPanel1.setBackground(Color.black);
             counter++;
             ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/11/11.jpg")));
             mt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money_tree/2500.jpg")));
             a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/11/11a.jpg")));
             b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/11/11b.jpg")));
             c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/11/11c.jpg")));
             d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question/11/11d.jpg")));
                  }
              }       
          };
          timer2.schedule(task2,0,500);
       
        }
        else {
 
 jPanel1.setBackground(Color.RED);
 timer.cancel();
 a.setVisible(false);
 b.setVisible(false);
 c.setVisible(false);
 d.setVisible(false);
 
          }
    }                                 

    /**
     * @param args the command lines arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front().setVisible(true);
            }
        });
    }

    // Variables declaration                   
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.JButton c;
    private javax.swing.JButton d;
    private javax.swing.JLayeredPane diagmsg;
    private javax.swing.JLabel hh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ll1;
    private javax.swing.JButton ll2;
    private javax.swing.JButton ll3;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel mt;
    private javax.swing.JLabel ques;
    private javax.swing.JLabel ss;
    // End of variables declaration                   

    void setVisble(boolean b) {
        this.setVisible(true);
    }

  
}
